name = "KalmanFilterToolbox"
uuid = "f63bbba1-7f9b-4c97-88ca-14c23099b99d"
authors = ["Nathanael Bosch <nathanael.bosch@uni-tuebingen.de> and contributors"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"

[compat]
ForwardDiff = "0.10"
SpecialMatrices = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
